### ISSUE TITLE
413 error on torrent upload

### ISSUE THREAD

**Issue by shellac** [academictorrents/academictorrents-docs#23]
I'm trying to submit an updated version of a torrent, which is 7.3MB.

On submission I get the error:

    413 Request Entity Too Large

Is there any way around this? Larger piece sizes perhaps?

(And thanks very much for this service)

**Comment by shellac** [comment]
Having said that I found 'Has this torrent been superseded by another torrent' may have done what I needed, without a new record.

An option to supply a URL (like the above) would be a useful general work around.

**Comment by ieee8023** [comment]
Sorry for this error. Our new server was not configured with the correct limits. Can you try it again?

Larger pieces will reduce the torrent file size and we recommend that you have piece sizes of 8192 or 16384 bytes because it will work better with faster connections.

In order to use "Has this torrent been superseded by another torrent" you still need to have another torrent to point it to. It just puts a banner on the page that links to the new torrent. It shows up like this: https://academictorrents.com/details/9512a1f6d21e5012c06a1c9b8e2dd4796ecc77a9

**Comment by shellac** [comment]
Ah, thanks very much for the tip about the piece sizes. I'm creating a new one, and will try it again.

(Ah, so I did understand the superseding, but can't see it: https://academictorrents.com/details/cc2d9afabcbbe33686d2ecd9844b534e3a899f4b)

**Comment by ieee8023** [comment]
The superseded value needs to be a link or hash of a torrent on Academic Torrents.

**Comment by shellac** [comment]
That seems to be working now. Thanks for your help.
