### ISSUE TITLE
Search API not available anymore

### ISSUE THREAD

**Issue by LightDestory** [academictorrents/academictorrents-docs#29]
The documentation 1.0 describes a entries search API but the it is not a usable endpoint...

Any idea on what happened? Search API has been deprecated without any notice?

**Comment by ieee8023** [comment]
The search API was turned off because there was an insane amount of non academic searches which was degrading service.

A scalable approach for us is to download a database feed which is updated daily and then perform a local search.
```https://academictorrents.com/database.xml```

I will update the documentation for the API soon and add more info about this xml feed. Sorry about that.

**Comment by LightDestory** [comment]
I am going to close this because the issue has been addressed. But I found some inconsistences on the xml. I will open a new issue.
