### ISSUE TITLE
recommended piece size too small?

### ISSUE THREAD

**Issue by carandraug** [academictorrents/academictorrents-docs#34]
The recommended piece size on the FAQ is "8192 or 16384 *bytes*":

> We recommend relativly large piece sizes (8192 or 16384 bytes) because academic connections are typically good enough to not produce errors at this size and a very large file with a small piece size could yield so many pieces that it is a computational burden to download it.

However, this seems a very small value considering the context. The recommendation is effectively 8 or 16kb which is a really low number, even for small non academic torrents. Maybe the documentation meant to say "8192 or 16384 *kibibytes*")? That would appear a more reasonable value for large files although I remember reading once to avoid piece sizes above 2048 kibibytes (I think a limit on old clients but I may be misremembering).

Anyway, I think the recommendation is wrong and I was hoping either some clarification or correction.

**Comment by ieee8023** [comment]
Yes you are right. I'll make the fix. Thanks!

It should be KiB. Larger piece sizes it can make a brittle connection have issues downloading because 16mb in one go may be a lot. But for TB size datasets having so many small pieces adds too much overhead and the .torrent files can be huge. New clients at least are able to handle larger piece sizes fine.
